### ISSUE TITLE
Tuplet conversion feedback/issues

### ISSUE THREAD

**Issue by eyrieowl** [lgvr123/musescore-durationeditor#1]
Hi, I wanted to provide some feedback on the tuplet conversion/duration editing based on the usage I just did.

First, technical details:  using plugin version 1.3.0beta1, in MuseScore 3.6.2 on Linux.

Task: I was transcribing a piece to create an arrangement for my use, and I'd started off in 4/4.   Along the way, I realized that I'd made a mistake, I was having to do too many complicated tuplets and I should have done 12/8 instead.  Someone in the forums suggested the plugin might help.  And it did!  However, there were a few issues I ran into.  I will also attach the file I was starting with.

First, the bugs/gotchas:  

1.  If I had a measure in 4/4 with 4 triplets, and I started converting tuplets at the start of the measure, I would end up with some rests inserted in the middle of my set of 12 notes.  However, if I started with the last triplet, and worked backwards, I would end up at the end with 12 eighth notes as expected with no rests.
2.  If I had a measure of 4 quarter notes, and I used the plugin to change them each to dotted quarter, it would end up converting the first eighth note of the subsequent measure to an 8th rest and an 8th note, where before it had been a quarter note. In order to get around this, I inserted blank measures between each of the measures in my file before starting, and then I deleted all those extra measures before changing the time signature at the end of my conversion process.  Also, for some reason, for the final measure, I had to insert *2* blank measures after it or the tuplet conversion wouldn't work right.

Next, the ask: I think what you have here is excellent, and it saved me a lot of time. One thing that, as you might guess, would be super helpful and I think you have the machinery to do would be to enable selecting multiple tuplets and selecting convert, instead of having to go one at a time.  And, of course, the absolutely nirvana would to be able to select a whole set of measures and do the full conversion from the current time signature to a new time signature, treating the existing notes as fractions of a measure rather than as fractions of the time base.

Anyhow, thanks for this plugin, hopefully that feedback helps, let me know if you have any questions about what I experienced or what I'd like to see.

[Marigolds_kishiBashi.mscz.zip](https://github.com/lgvr123/musescore-durationeditor/files/8680662/Marigolds_kishiBashi.mscz.zip)

**Comment by lgvr123** [comment]
> I would end up with some rests inserted in the middle of my set of 12 notes.

Will try to reproduce what you are exactly observing.

About your other remarks, a first observation is that converting 4/4 to 12/8 isn't something easy for MS. I never tried this before. My first attempt had been to convert all the triplets to eights and all the quarter to dotted-quarters with my plugin. The measure has then 12 eights. Fine. It should be easy to change the 4/4 to a 12/8. Not for MS that complains about the measure being invalid (and it is : the measure is a 4/4 measure with 12 eights). However MS shouldn't complain about that, in this case, as we are trying to regularize the situation.
Working the opposite way, meaning first changing the measure from 4/4 to 12/8 then every measure will eat a little bit from the next one in order to be filled in. That's where you used your workaround and inserted blank measures. Again, this should be raised at the level of MuseScore, not as an issue, but as feature request : being able to change the TimeSignature without eating from the next measure.
For both points, there is little I can do at the level of the plugin. Except adding a new feature that will regularize a 4/4 measure with 12 eights to 12/8. I will note this on my todo list ;-)

Concerning, you request of converting multiple tuplets at once, it will not be done at the level of the plugin, because converting one tuplet is a lot of cheating/tweaking/copy/paste/... (you can observe this by the number of undos needed to undo one conversion). The plugin was actually made as Proof-Of-Concept that there was a need to have other ways of working in MS and other ways where possible. I think the demonstration is done and even the MS guru (Mark Sabatella) has been convince that it was useful. The next step would be to implement this directly in MuseScore, and no longer as a plugin where the API is pretty limited and not flawless.

Sorry not to have answered really positively to your remarks. Thanks anyway to have shared them. I appreciate it. And I will get back to you with the "inserted rest" issue.

**Comment by lgvr123** [comment]
Hi, there is new version available that fixes your first issue.

About your remarks about TimeSignature conversion, my previous answer was incorrect:

_"My first attempt had been to convert all the triplets to eights and all the quarter to dotted-quarters with my plugin. The measure has then 12 eights. Fine. It should be easy to change the 4/4 to a 12/8. Not for MS that complains about the measure being invalid (and it is : the measure is a 4/4 measure with 12 eights). However MS shouldn't complain about that, in this case, as we are trying to regularize the situation."_ : This is incorrect. It is working, but all the staves have to be adapted before being able to tod the conversion:
![Marigolds_kishiBashi](https://user-images.githubusercontent.com/50494/170220725-57ecd789-40c7-4676-a0ba-4a41b3ff6f76.gif)
